name: just66
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  card_swiper: ^1.0.4
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  fl_chart: ^0.40.6
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.1.5
  font_awesome_flutter: ^9.2.0
  intl: ^0.17.0
  liquid_progress_indicator: ^0.4.0
  package_info_plus: ^1.3.0
  path: ^1.8.1
  path_provider: ^2.0.8
  provider: ^6.0.1
  sqflite: ^2.0.1
  sqlbrite: ^2.2.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icons/logo.png"
  adaptive_icon_background: "assets/icons/logo_background.png"
  adaptive_icon_foreground: "assets/icons/logo_foreground.png"
flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Medium.ttf
        - asset: fonts/Poppins/Poppins-MediumItalic.ttf
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
